### ISSUE TITLE
aeon.exceptions.CommandError not providing useful error info

### ISSUE THREAD

**Issue by bobbywatson3** [Apstra/aeon-venos#19]
```
Traceback (most recent call last):
  File "/opt/aeonztps/bin/aos-installer-eos", line 363, in <module>
    main()
  File "/opt/aeonztps/bin/aos-installer-eos", line 349, in main
    dev = Device(target=target, user=user, passwd=passwd)
  File "build/bdist.linux-x86_64/egg/aeon/eos/device.py", line 38, in __init__
  File "build/bdist.linux-x86_64/egg/aeon/eos/device.py", line 49, in gather_facts
  File "build/bdist.linux-x86_64/egg/aeon/eos/connector.py", line 39, in execute
aeon.exceptions.CommandError
```

According to the code, it's supposed to show the message of the underlying exception:
```python
class CommandError(Exception):
    def __init__(self, exc, commands):
        super(CommandError, self).__init__()
        self.exc = exc
        self.commands = commands

    def __repr__(self):
        return self.exc.message
```

**Comment by bobbywatson3** [comment]
resolved in #20
